### ISSUE TITLE
TXT conversion skips over carriage returns that have no following line feed

### ISSUE THREAD

**Issue by efieleke-tausight** [docwire/docwire#140] opened 2024-07-09 21:19 UTC
If a txt file has the following:

foo\rbar

Notepad and Notepad++ display the above text in two lines:

foo
bar

But docwire returns "foobar" for the converted text.

A carriage return all by itself is best returned as-is (is our view).

This problem is happening in docwire 2024.06.24. The previous doc to text did not behave this way. Given "foo\rbar" it returned "foo\rbar"

**Comment by efieleke-tausight** [comment] 2024-07-09 21:21
For reference, here is how we call into docwire. In this case, GetMappedExtension is returning "txt" (and the file is a UTF8 text file without any BOM).

```
	auto iStream = std::make_shared<boost::iostreams::stream<boost::iostreams::array_source>>(buffer, bufferSize);

	docwire::data_source dataSource(
		docwire::seekable_stream_ptr { iStream },
		docwire::file_extension("." + GetMappedExtension(extension)));

	std::basic_stringstream<char> outStream;

	std::move(dataSource) | 
		docwire::ParseDetectedFormat<docwire::OfficeFormatsParserProvider, docwire::MailParserProvider, 
 docwire::OcrParserProvider>(_parameters) |
		docwire::PlainTextExporter() |
		outStream;

```

**Comment by as-ascii** [comment] 2024-07-19 17:45
Hello,

The issue is confirmed. The \r as end of line character is very old approach from classic Mac OS:
https://en.wikipedia.org/wiki/Newline
This scenario was not included during one of the refactorings. Currently the end of line symbols are normalized and there is always single \n on output. Single \r is lost during the normalization. It needs to be fixed and regression test for this scenario should be added.

Planned improvements:
- Treat single \r as end of line character
- Send docwire::tag::BreakLine (on single EOL) and docwire::tag::Paragraph (for all double EOL separated parts) instead of single docwire::tag::Text for whole input file.
- This will let PlainTextExporter or user-defined exporter decide about EOL characters in output
- This will improve exporting to other formats like HTML
- This will allow incremental parsing and exporting for large files

**Comment by pcoramasionwu** [comment] 2024-08-06 13:11
Expected Outcome: "\r" chars are preserved in document conversion. (Given "foo\rbar" as input in the source document, SDK returns "foo\rbar".)

**Comment by as-ascii** [comment] 2024-08-06 13:59
We think that end-of-line characters in output (from PlainTextExporter) should be normalized and consistent by default to minimize effort on app-developer side. It can be configurable to select CRLF, CR or LF. In addition if it is required to preserve original EOL characters from input it can be available as an option (can be stored in additional field of BreakLine structure and restored by PlainTextExporter).

**Comment by pcoramasionwu** [comment] 2024-08-07 11:05
Havin it preserve the original input characters as an option would be acceptable

**Comment by as-ascii** [comment] 2024-08-09 18:55
We have this implemented but it will be merged later, together with other improvements.
- PlainTextParser recognizes all 3 EOL types.
- It converts EOLs to tag::BreakLine, recognizes paragraphs and wrap them inside tag::Paragraph and tag::CloseParagraph. 
- It has two additional parameters: parse_lines, parse_paragraphs. If set to false the parser is preserving original EOLs and put them inside tag::Text.
- PlainTextExporter has additional constructor argument eol_sequence (\n by default) that can be used to normalize EOLs to selected type.

**Closed** 2024-08-26 00:13 UTC
