### ISSUE TITLE
Library is getting crashed while parsing few eml files

### ISSUE THREAD

**Issue by skothala09** [docwire/docwire#90] opened 2024-01-30 10:28 UTC
Hi Team, 
Below are the issues that we are facing while we are using the doctotext library(version 5.0.9)
**Issue1:**
As reported earlier we are facing crash issues while we are parsing few .eml files. The same has been reported via email some time back.
Attaching few samples for your reference
[SegmentationFault.zip](https://github.com/docwire/docwire/files/14096392/SegmentationFault.zip)
.

**Issue2:**
Everytime we are getting below message, please help us in understanding this and and how can we remove this
"Error loading plugin: boost::dll::shared_library::load() failed (dlerror system message: libwebpmux.so.3: cannot open shared object file: No such file or directory): Bad file descriptor [generic:9]"

**Issue3:**
we are having the base64 encoded string data, for which we need to extract the content. Please let us know the api for this. Currently we are writing this base64 encoded string to a temporary file and then we are extracting the content. This creation of temporary file is an extra overhead.

Please help in resolving the above issues.

**Comment by as-ascii** [comment] 2024-01-30 13:34
Hello,

Thank you for supporting DocWire SDK with reporting the issue.

We checked example files with the current version (linux build) and they are processed without segmentation fault. Could you please check using the latest release?
https://github.com/docwire/docwire/releases/tag/2024.01.05
or current github repository head.

Please also recheck the second issue with the latest version as there were some fixes in this area.

Regarding issue 3, there is no need for a temporary file. As you can see in the examples:
https://docwire.readthedocs.io/en/latest/#examples
 you can use any std::istream as an input and any std::ostream as an output in parsing chain. They can be memory streams like std::stringstream.

Unfortunately DocWire SDK does not provide direct access to base64 decoder right now. Decoding is executed as part of EML parsing but it needs EML headers etc. If you need direct access to base64 decoder we can probably add a separate transformer.

If your current base64 decoder that you use gives ability to incremental decoding, you can wrap it inside TransformerFunc like presented in the documentation or add new class derived from PipeChain. This way you can integrate base64 decoder with DocWire SDK without any temporary buffer.

Please let us know what is the results of upgrading SDK to latest version and in what direction would you like to go with base64 decoding. Maybe we do not understand the issue correctly.

Best regards.

**Comment by skothala09** [comment] 2024-01-31 06:54
Thank you for your reply and support.
Actually the hierarchy and the usage is completely different compared to the 5.0.9 version.
Can you please help me how to build the sample program. and currently in our project we are not using the cmake.

**Comment by as-ascii** [comment] 2024-01-31 18:20
What build system are you using currently?

**Comment by skothala09** [comment] 2024-02-01 05:30
We are using MPC and MWC from ACE library as our build system

**Comment by as-ascii** [comment] 2024-02-02 12:27
Unfortunately we do not have experience with this build system but as you have, you should be able to add required compiler and linker flags described in the vcpkg documentation:
https://learn.microsoft.com/en-us/vcpkg/users/buildsystems/manual-integration

If you use build.sh to compile DocWire or just download binaries from website you will receive the vcpkg binary directory with "installed" subdir described in the documentation.

With CMake it's easier of course as this is (good or bad) standard currently for C++ projects.

If you have any issues please paste the compiler log (command with flags and error messages).

Best regards.

**Comment by skothala09** [comment] 2024-02-05 00:34
Hi Team,

I am trying to link the latest docwire library from the release binaries to the sample code in ubuntu 20.04. I am getting below errors.
![image](https://github.com/docwire/docwire/assets/158155620/aa5aeda8-3d2c-41bf-8ff2-5befc6a90691)

But able to build in ubuntu 22.04 , but facing crash issue while executing
Please find the below snapshot
![image](https://github.com/docwire/docwire/assets/158155620/c1d0e222-f768-4044-8680-d7eaec015cb4)

**Currently our OS version is ubuntu 20.04 And we need this library compatible in this OS version only.**

And for build the library in ubuntu 20.04 we are trying to setup the vcpkg as mentioned but facing issues while we are trying to setup.
![image](https://github.com/docwire/docwire/assets/158155620/8dd01c5f-d6eb-4b7b-8797-ba5446cec361)

So please help us in resolving the issues and make use of the library

**Comment by skothala09** [comment] 2024-02-06 06:25
As suggested I have tried to run the docwire.sh script.. But I am getting below error
![image](https://github.com/docwire/docwire/assets/158155620/712138e8-be06-446b-9cef-9c8d96a5c63d)

And regarding the errors related to ubuntu 20.04, Mostly the libraries in the release are built in higher version of Ubuntu.. I have set the LD_LIBRARY_PATH as well. Please correct me if my understanding is wrong

**Comment by as-ascii** [comment] 2024-02-06 11:38
Please check if symbolic links, file size and resolving are correct using:
`ls -l ./installed/x64-linux-dynamic/tools/../lib/libcurlpp.so.1
ls -l ./installed/x64-linux-dynamic/tools/../lib/libcurlpp.so.1.0.0
ldd ./installed/x64-linux-dynamic/tools/../lib/libcurlpp.so.1.0.0`
It should give something like:
`vcpkg/installed/x64-linux-dynamic/tools/../lib/libcurlpp.so.1 -> libcurlpp.so.1.0.
159624 01-05 20:14 /home/adrian/Pobrane/docwire-2024.01.05/installed/x64-linux-dynamic/tools/../lib/libcurlpp.so.1.0.0
.. and all dependencies resolved`.

If symbolic links are incorrect please check the archive decompression method.

We will add Ubuntu 20.04 to CI very soon.
In addition you can try to build from sources using ./build.sh. It's long but usually fully automatic.

We will for sure find the solution for both platforms.

**Comment by as-ascii** [comment] 2024-02-07 11:13
Hello,

We tried to build SDK on Ubuntu 20.22 but it seems that the default compiler is gcc v9 and it's not supporting a lot of C++ features:
https://en.cppreference.com/w/cpp/compiler_support

Version 9 is very old, even comparing to Debian Stable:
```
$ gcc --version
gcc (Debian 12.2.0-14) 12.2.0
```
Are you using this version of GCC for your project or do you switch compiler to different version? If yes, to what version? Or do you use CLang maybe?

Please advice how to proceed to help.

**Comment by skothala09** [comment] 2024-02-07 11:54
Hi,

Currently we are using gcc version 9
![image](https://github.com/docwire/docwire/assets/158155620/2cf9b025-4dab-4111-888b-c3cfdf309b50)

In this case how can we proceed further.

**Comment by as-ascii** [comment] 2024-02-07 13:20
Could you consider upgrading the compiler? GCC 9 was fist released in 2019, GCC 10 is available since 2020 and current version (in 2024) is 13.2.
We are checking is it possible to build the current version of SDK with GCC 9 but problems can be inside dependencies as well. Even if we manage to rebuild it, we will probably not able to support in the the future as the SDK depends on C++20 standard.

What about the sharing library loading problem on Ubuntu 22.04? Did you manage to check the files integrity as described above? Are you able to build the SDK from sources using ./build.sh ?

**Comment by as-ascii** [comment] 2024-02-07 14:31
We are testing with different versions of gcc available on ubuntu 20.04 currently to detect what minimal version is required for successful build.

**Comment by as-ascii** [comment] 2024-02-07 15:40
It looks like gcc v11 is fine. These are commands for Ubuntu 22.04 to upgrade the compiler:
```
sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
sudo apt-get update
sudo apt-get install gcc-11 g++-11 -y
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 110 --slave /usr/bin/g++ g++ /usr/bin/g++-11
sudo update-alternatives --set gcc /usr/bin/gcc-11
```
Please keep in mind that we are not experts in Ubuntu 20 administration so maybe there is simpler/safer method to upgrade the compiler on this platform.

**Comment by skothala09** [comment] 2024-02-07 15:47
Actually we need the library in ubuntu 20.04.
In this ubuntu version can we update the gcc 11?

**Comment by skothala09** [comment] 2024-02-07 16:42
After updating the gcc version ran the build.sh script and it is failing at 120 step

Error Message:

Installing 120/122 unzip:x64-linux-dynamic...
Building unzip:x64-linux-dynamic...
warning: -- Using community triplet x64-linux-dynamic. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: /mnt/d/Docwire/docwire/vcpkg/triplets/community/x64-linux-dynamic.cmake
-- Installing port from location: /mnt/d/Docwire/docwire/./ports/unzip
-- Downloading http://www.winimage.com/zLibDll/unzip101e.zip -> unzip101e.zip...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Trying to load bundleconfig from /mnt/d/Docwire/docwire/vcpkg/vcpkg-bundle.json
[DEBUG] Failed to open: /mnt/d/Docwire/docwire/vcpkg/vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
[DEBUG] Metrics enabled.
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Feature flag 'dependencygraph' unset
[DEBUG] 1000: execute_process(curl --fail -L http://www.winimage.com/zLibDll/unzip101e.zip --create-dirs --output /mnt/d/Docwire/docwire/vcpkg/downloads/unzip101e.zip.10464.part)
[DEBUG] 1000: cmd_execute_and_stream_data() returned 0 after   716811 us
[DEBUG] Trying to hash /mnt/d/Docwire/docwire/vcpkg/downloads/unzip101e.zip.10464.part
[DEBUG] /mnt/d/Docwire/docwire/vcpkg/downloads/unzip101e.zip.10464.part has hash d1e4540d49f8c55a58aeed8cc166cb0ccf02ded59844b3131858630c0b16c36a7aa8925d16ec5a1a12e099facd51ca46a29ffd8f91ee9c117824303dbd1e702f
error: Failed to download from mirror set
error: File does not have the expected hash:
url: http://www.winimage.com/zLibDll/unzip101e.zip
File: /mnt/d/Docwire/docwire/vcpkg/downloads/unzip101e.zip.10464.part
Expected hash: f09ca22be674ef3813428120f756a74f2b46f83035a4bb1ad7f39b41f1ff1f6d83d5c7d07e9d2b8eb6de543209ea7eb4b2e36ecb2a2758a40477189ee5658339
Actual hash: d1e4540d49f8c55a58aeed8cc166cb0ccf02ded59844b3131858630c0b16c36a7aa8925d16ec5a1a12e099facd51ca46a29ffd8f91ee9c117824303dbd1e702f
[DEBUG] /mnt/vss/_work/1/s/src/vcpkg/base/downloads.cpp(1048):
[DEBUG] Time in subprocesses: 716811us
[DEBUG] Time in parsing JSON: 27us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 786us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 738 ms (735625us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):

      Failed to download file with error: 1
      If you are using a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.

      3. Your proxy's remote server is out of service.

      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.


Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  /mnt/d/Docwire/docwire/ports/unzip/portfile.cmake:1 (vcpkg_download_distfile)
  scripts/ports.cmake:170 (include)


> error: building unzip:x64-linux-dynamic failed with: BUILD_FAILED
> Elapsed time to handle unzip:x64-linux-dynamic: 1.7 s
> Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
> Then check for known issues at:
>   https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+unzip
> You can submit a new issue at:
>   https://github.com/microsoft/vcpkg/issues/new?title=[unzip]+Build+error+on+x64-linux-dynamic&body=Copy+issue+body+from+%2Fmnt%2Fd%2FDocwire%2Fdocwire%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by as-ascii** [comment] 2024-02-08 02:20
Can be temporary problem (seems like something with downloading/hosting/proxy), today we rebuilded it several times and it worked.
Anyway, we already have this configuration in the CI so after some final touches we should be able to deliver you tomorrow binary artefacts as well.

**Comment by as-ascii** [comment] 2024-02-08 02:23
```
wget http://www.winimage.com/zLibDll/unzip101e.zip
...
sha512sum unzip101e.zip 
f09ca22be674ef3813428120f756a74f2b46f83035a4bb1ad7f39b41f1ff1f6d83d5c7d07e9d2b8eb6de543209ea7eb4b2e36ecb2a2758a40477189ee5658339  unzip101e.zip
```
Seems to have expected hash currently, so it should work.

**Comment by skothala09** [comment] 2024-02-08 05:58
Hi team,

I am not clear with this.. what are the steps to be followed

$ wget http://www.winimage.com/zLibDll/unzip101e.zip
...
$ sha512sum unzip101e.zip 
f09ca22be674ef3813428120f756a74f2b46f83035a4bb1ad7f39b41f1ff1f6d83d5c7d07e9d2b8eb6de543209ea7eb4b2e36ecb2a2758a40477189ee5658339  unzip101e.zip

**Comment by as-ascii** [comment] 2024-02-08 10:34
Hello,

It is not a new step, I just checked manually (using these commands) that the download that vcpkg complained about is working correctly. If you have same result than it was a temporary connection problem on client or server side.

In the meantime: we are finishing Ubuntu 20.04 binary archive for you.

**Comment by as-ascii** [comment] 2024-02-08 10:47
Good news, the error with OpenSSL legacy providers (your screenshot below) was reproduced in our environment with ubuntu 20 build so we will be able to investigate.
> But able to build in ubuntu 22.04 , but facing crash issue while executing Please find the below snapshot ![image](https://private-user-images.githubusercontent.com/158155620/302145337-c1d0e222-f768-4044-8680-d7eaec015cb4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczODg1ODYsIm5iZiI6MTcwNzM4ODI4NiwicGF0aCI6Ii8xNTgxNTU2MjAvMzAyMTQ1MzM3LWMxZDBlMjIyLWY3NjgtNDA0NC04NjgwLWQ3ZWFlYzAxNWNiNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwOFQxMDMxMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYTAyNDU2NTJlNjYwZDYwZjdjYjFhNmI5OTc0N2VkMjY2ZmZjZWJmZTE0OWRjZDkyZWU0OGE4ZTVjNDI2NzEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.y7GmngVqnNbh07E_0qhRFXRx5hkl8TO10d4hIZyqcT4)

**Comment by skothala09** [comment] 2024-02-08 10:49
Hi Team,
 The sha512sum is different at my end
![image](https://github.com/docwire/docwire/assets/158155620/675f56b9-25fa-4c29-8222-7000774cd5cc)

**Comment by as-ascii** [comment] 2024-02-08 11:15
Ubuntu 20.04 binaries are available here:
https://github.com/docwire/docwire/actions/runs/7823967829
bottom of the screen, in the artifacts.

We are investigating the openssl issue but it can be related with moving the binary to other Linux distribution as all automatic tests during the build passed. It can be also related with different linker environment variables between automatic tests and example runs. All should be clear soon.

I think that gcc is almost-fully backward compatible (source code) but for sure it is possible that recompiling of binaries will be required. We tried with older compiler but it is not only our code, some of Microsoft-delivered dependencies in VCPKG repository also refused to work.

**Comment by as-ascii** [comment] 2024-02-08 11:22
It seems that file that you are receiving is text/html not application/zip. Please check the text content of the file, there can be some important message there.

> Hi Team, The sha512sum is different at my end ![image](https://private-user-images.githubusercontent.com/158155620/303300193-675f56b9-25fa-4c29-8222-7000774cd5cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczOTA4MDksIm5iZiI6MTcwNzM5MDUwOSwicGF0aCI6Ii8xNTgxNTU2MjAvMzAzMzAwMTkzLTY3NWY1NmI5LTI1ZmEtNGMyOS04MjIyLTcwMDA3NzRjZDVjYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwOFQxMTA4MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZGY4NGM3OGZmOTk3Zjc0MWMwY2YxNmI0MDU3NzI2NzZmZDcxOGNlNjg3ZTM3OWUyYzBlMDMwZjc0ZTE3ZTlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ke8ZnzDiieZWhdcGxlKU7syfc-ndNWiacUMd3c3g75I)

**Comment by skothala09** [comment] 2024-02-08 11:40
With the 20.04 binaries I am able to build the sampel code but getting the same OpenSSL errors
![image](https://github.com/docwire/docwire/assets/158155620/c0c455fc-ba54-46e4-a1d9-b0dd05e70b67)

**Comment by as-ascii** [comment] 2024-02-08 12:01
Yes, confirmed on clean Ubuntu 20 docker image. We are now investigating the issue. Please keep in mind that (as the error message shows) it is an error from 3rdparty library but it can be still possible to patch it or workaround it probably. We are really trying to deliver working Ubuntu 20 solution. The strange thing is that automatic test binary (api_tests) works fine. So there is hope.

**Comment by as-ascii** [comment] 2024-02-08 12:55
Ok, the issue is temporarily resolved. Please check on the screenshot below how we set additional environment variable to resolve the error. Of course we (or upstream) have to fix the issue in another way later so it will be more user-friendly. Please let us know if the hot-fix works.
![obraz](https://github.com/docwire/docwire/assets/62467072/330e70fa-c74d-4c89-8c53-d4df515810f9)

**Comment by skothala09** [comment] 2024-02-08 17:11
The hot-fix worked 👍 . I am able to build and run the sample code.

**Comment by as-ascii** [comment] 2024-02-08 17:46
That is great.

Please check problematic EML files (issue 1) and ""Error loading plugin: boost::dll::shared_library::load() failed (dlerror system message: libwebpmux.so.3: cannot open shared object file: No such file or directory): Bad file descriptor [generic:9]" (issue 2) and base64 decoding situation (issue 3) so we can close the github issue.

**Comment by as-ascii** [comment] 2024-02-25 17:40
Important changes related to this issue introduced in linked, merged pull request:
- Add Ubuntu 20.22 GitHub runner to continuous integration (automatic tests)
- Add basic automatic test for running DocWire CLI
- Add setup_env.sh and setup_env.ps1 scripts for setting up environment instead of docwire.sh and docwire.bat CLI wrappers
- Update installation documentation

**Comment by as-ascii** [comment] 2024-03-19 17:41
Upstream links:
https://github.com/podofo/podofo/issues/135
https://github.com/microsoft/vcpkg/discussions/36715

**Comment by as-ascii** [comment] 2024-03-27 02:28
The OpenSSL issue is continued in #110 and this issue will be closed now. Please reopen or (better) create a new dedicated issue if any of reported problems is not fixed.

**Closed by as-ascii** 2024-03-27 02:28 UTC
