### ISSUE TITLE
Subject Line is not getting extracted in the eml file

### ISSUE THREAD

**Issue by skothala09** [docwire/docwire#100] opened 2024-03-19 10:50 UTC
Hi Team,

While testing it is identified that the subject line of the eml files is not getting extracted. Can you please check and let us know.

**Comment by as-ascii** [comment] 2024-04-04 16:10
Hello,

The issue was confirmed: #121 . The code for extracting a lot of metadata from eml file, including the subject is embedded inside the SDK, however tag::Metadata is not correctly emitted to the parsing chain. It looks like a trivial bug but we would like to add some missing automatic tests for this as well so it will never return.

**Comment by skothala09** [comment] 2024-04-26 10:36
Hi Team,

Can you please provide an update on this issue

**Comment by as-ascii** [comment] 2024-05-06 13:57
Hello,

The problem was found and fixed but it was not merged yet to the main branch as it is part of larger changes that are under performance testing. We are planning to merge it this week.

**Comment by as-ascii** [comment] 2024-06-19 23:02
The branch with the fix was merged. Currently if you receive tag::Document from the SDK you can use metadata function field to parse and retrieve metadata. Metadata exporting was added to HTML exporter as well. It was not added to plain text exporter as we currently don't have an idea how it should look like. It can be discussed (please reopen this issue or create another one if you think that metadata should be exported by plain text exporter as well).

**Closed by as-ascii** 2024-06-19 23:02 UTC
